apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-gateway-api-deployment
  labels:
    app: delivery-gateway-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-gateway-api
  template:
    metadata:
      labels:
        app: delivery-gateway-api
    spec:
      containers:
        - name: delivery-gateway-api
          image: paradocx96/delivery-gateway-api:{{tag}}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 0.2
              memory: 350Mi
            limits:
              cpu: 0.5
              memory: 500Mi
