apiVersion: v1
kind: Service
metadata:
  name: delivery-gateway-api-service
spec:
  type: LoadBalancer
  selector:
    app: delivery-gateway-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
